# -*- mode: ruby -*-
# vi: set ft=ruby :

CPU=1
RAM=1024
IP1="10.0.0.10"
IP2="10.0.0.11"
IP3="10.0.0.12"

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.network "private_network", ip: IP1
    lb.vm.hostname = "lb"
    lb.hostsupdater.aliases = ["lb"]

    lb.vm.provider "virtualbox" do |v|
      v.memory=RAM
      v.cpus=CPU
    end

  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.network "private_network", ip: IP2
    web1.vm.hostname = "web1"
    web1.hostsupdater.aliases = ["web1"]

    web1.vm.provider "virtualbox" do |v|
      v.memory=RAM
      v.cpus=CPU
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.network "private_network", ip: IP3
    web2.vm.hostname = "web2"
    web2.hostsupdater.aliases = ["web2"]

    web2.vm.provider "virtualbox" do |v|
      v.memory=RAM
      v.cpus=CPU
    end
  end
end
