# -*- mode: ruby -*-
# vi: set ft=ruby :

CPU=1
RAM=1024
IP="10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "labgate/nginx"

  config.vm.network "private_network", ip:IP
  config.vm.hostname="nginx"
  config.vm.synced_folder "static-website-example/", "/usr/share/nginx/html"

  config.vm.provider "virtualbox" do |v|
    v.memory=RAM
    v.cpus=CPU
  end
end
